spring.application.name=kiki
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/kiki_db
spring.datasource.username=temi
spring.datasource.password=2009
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=x7Kp9vQ2mR8tYw3zA5nL1cB6dF4hJ0sE9uV2gM7xK3pQ8rT5wZ
jwt.expiration=86400000